// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZrSSGRV-veMXZjV9ttAAeWJHkSxBroY',
    appId: '1:458844546661:web:274508db4f6a98082b488c',
    messagingSenderId: '458844546661',
    projectId: 'pagina-boton',
    authDomain: 'pagina-boton.firebaseapp.com',
    storageBucket: 'pagina-boton.appspot.com',
    measurementId: 'G-JPD4MJFYE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZZpVACBCP7HwLPK_VErn4Y4L6vrCkYsg',
    appId: '1:458844546661:android:7738b2a43c9bd0ae2b488c',
    messagingSenderId: '458844546661',
    projectId: 'pagina-boton',
    storageBucket: 'pagina-boton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApF08fNCEwha3bpiQnl-XvjB64L4qeWTU',
    appId: '1:458844546661:ios:1c705739b4d2d8822b488c',
    messagingSenderId: '458844546661',
    projectId: 'pagina-boton',
    storageBucket: 'pagina-boton.appspot.com',
    iosBundleId: 'com.example.paginaBoton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApF08fNCEwha3bpiQnl-XvjB64L4qeWTU',
    appId: '1:458844546661:ios:1c705739b4d2d8822b488c',
    messagingSenderId: '458844546661',
    projectId: 'pagina-boton',
    storageBucket: 'pagina-boton.appspot.com',
    iosBundleId: 'com.example.paginaBoton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArZrSSGRV-veMXZjV9ttAAeWJHkSxBroY',
    appId: '1:458844546661:web:767b03ae09a98c8b2b488c',
    messagingSenderId: '458844546661',
    projectId: 'pagina-boton',
    authDomain: 'pagina-boton.firebaseapp.com',
    storageBucket: 'pagina-boton.appspot.com',
    measurementId: 'G-J3446NNHQ7',
  );
}
